"""org trial_used field

Revision ID: 18f9bf0894e7
Revises: 89dbfc8a651d
Create Date: 2026-08-04 03:52:31.028407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18f9bf0894e7'
down_revision: Union[str, Sequence[str], None] = '89dbfc8a651d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('trial_used', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'trial_used')
    # ### end Alembic commands ###
