"""platform analytics tables

Revision ID: 89be348dc152
Revises: 13069cf9ba31
Create Date: 2026-08-03 02:06:11.212704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89be348dc152'
down_revision: Union[str, Sequence[str], None] = '13069cf9ba31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_call_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('signup', 'plan_changed', 'activated', 'deactivated', 'subscription_created', 'subscription_updated', 'subscription_canceled', 'payment_failed', name='orgeventtype'), nullable=False),
    sa.Column('from_plan', sa.String(length=20), nullable=True),
    sa.Column('to_plan', sa.String(length=20), nullable=True),
    sa.Column('subscription_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('organizations', sa.Column('subscription_status', sa.String(length=30), nullable=True))
    op.add_column('organizations', sa.Column('referral_code', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('referred_by_org_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'organizations', ['referral_code'])
    op.create_foreign_key(None, 'organizations', 'organizations', ['referred_by_org_id'], ['id'])
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'referred_by_org_id')
    op.drop_column('organizations', 'referral_code')
    op.drop_column('organizations', 'subscription_status')
    op.drop_table('organization_events')
    op.drop_table('ai_call_logs')
    op.drop_table('error_logs')
    # ### end Alembic commands ###
