"""org document template fields

Revision ID: 89dbfc8a651d
Revises: 89be348dc152
Create Date: 2026-08-03 06:47:04.469241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89dbfc8a651d'
down_revision: Union[str, Sequence[str], None] = '89be348dc152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('doc_template_lease_agreement', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('doc_template_lease_renewal_notice', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('doc_template_rent_increase_notice', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('doc_template_move_out_notice', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'doc_template_move_out_notice')
    op.drop_column('organizations', 'doc_template_rent_increase_notice')
    op.drop_column('organizations', 'doc_template_lease_renewal_notice')
    op.drop_column('organizations', 'doc_template_lease_agreement')
    # ### end Alembic commands ###
