"""org trial_ends_at field

Revision ID: afa06c7073ee
Revises: 18f9bf0894e7
Create Date: 2026-08-04 04:09:10.636601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa06c7073ee'
down_revision: Union[str, Sequence[str], None] = '18f9bf0894e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'trial_ends_at')
    # ### end Alembic commands ###
