"""org api_key field

Revision ID: b6e9733d2bc7
Revises: afa06c7073ee
Create Date: 2026-08-04 05:00:23.600237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e9733d2bc7'
down_revision: Union[str, Sequence[str], None] = 'afa06c7073ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('api_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_organizations_api_key'), 'organizations', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_api_key'), table_name='organizations')
    op.drop_column('organizations', 'api_key')
    # ### end Alembic commands ###
